# Generated by Django 3.2.12 on 2022-02-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_time',
        ),
    ]
