# Generated by Django 3.2.12 on 2022-02-16 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
